package com.tresfocus.ekart.hibernate.entity;

// Generated Jul 13, 2014 8:45:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Cities generated by hbm2java
 */
@XStreamAlias("city")
@Entity
public class Cities implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private States states;
	private String name;
	@XStreamOmitField	
	@JsonIgnore
	private Set zones = new HashSet(0);

	public Cities() {
	}

	public Cities(States states, String name) {
		this.states = states;
		this.name = name;
	}

	public Cities(States states, String name, Set zones) {
		this.states = states;
		this.name = name;
		this.zones = zones;
	}

	public Cities(Integer cityId) {
		this.id = cityId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getZones() {
		return this.zones;
	}

	public void setZones(Set zones) {
		this.zones = zones;
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("states", States.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
