package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Country generated by hbm2java
 */
@XStreamAlias("country")
@Entity
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String isoCode2;
	private String isoCode3;
	private String addressFormat;
	private boolean postcodeRequired;
	private boolean status;
	@XStreamOmitField	
	@JsonIgnore
	private Set stateses = new HashSet(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set<Address> addresses = new HashSet<Address>(0);

	public Country() {
	}

	public Country(String name, String isoCode2, String isoCode3,
			String addressFormat, boolean postcodeRequired, boolean status) {
		this.name = name;
		this.isoCode2 = isoCode2;
		this.isoCode3 = isoCode3;
		this.addressFormat = addressFormat;
		this.postcodeRequired = postcodeRequired;
		this.status = status;
	}

	public Country(String name, String isoCode2, String isoCode3,
			String addressFormat, boolean postcodeRequired, boolean status,
			Set<Address> addresses) {
		this.name = name;
		this.isoCode2 = isoCode2;
		this.isoCode3 = isoCode3;
		this.addressFormat = addressFormat;
		this.postcodeRequired = postcodeRequired;
		this.status = status;
		this.addresses = addresses;
	}

	public Country(Integer countryId) {
		this.id = countryId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIsoCode2() {
		return this.isoCode2;
	}

	public void setIsoCode2(String isoCode2) {
		this.isoCode2 = isoCode2;
	}

	public String getIsoCode3() {
		return this.isoCode3;
	}

	public void setIsoCode3(String isoCode3) {
		this.isoCode3 = isoCode3;
	}

	public String getAddressFormat() {
		return this.addressFormat;
	}

	public void setAddressFormat(String addressFormat) {
		this.addressFormat = addressFormat;
	}

	public boolean isPostcodeRequired() {
		return this.postcodeRequired;
	}

	public void setPostcodeRequired(boolean postcodeRequired) {
		this.postcodeRequired = postcodeRequired;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set getStateses() {
		return this.stateses;
	}

	public void setStateses(Set stateses) {
		this.stateses = stateses;
	}
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Country [id=");
		builder.append(id);
		builder.append(", name=");
		builder.append(name);
		builder.append(", isoCode2=");
		builder.append(isoCode2);
		builder.append(", isoCode3=");
		builder.append(isoCode3);
		builder.append(", addressFormat=");
		builder.append(addressFormat);
		builder.append(", postcodeRequired=");
		builder.append(postcodeRequired);
		builder.append(", status=");
		builder.append(status);
		builder.append("]");
		return builder.toString();
	}
	
	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
