package com.tresfocus.ekart.hibernate.entity;

import java.util.Date;

import javax.persistence.Version;

import org.hibernate.annotations.Entity;

import com.thoughtworks.xstream.annotations.XStreamAlias;

// Generated May 3, 2014 1:17:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * CustomerRetailer generated by hbm2java
 */
@XStreamAlias("customer_retiler")
@Entity
public class CustomerRetailer implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int id;
	private User userByCustomerId;
	private User userByRetailerId;
	private Date creationDate;
	private Date lastUpdatedDate;
	private int createdBy;
	private int lastUpdatedBy;
	@Version
	private int objectVersionNumber;
	
	public CustomerRetailer() {
	}

	public CustomerRetailer(User userByCustomerId, User userByRetailerId,
			int createdBy, int lastUpdatedBy, Date creationDate,
			Date lastUpdatedDate, int objectVersionNumber) {
		this.userByCustomerId = userByCustomerId;
		this.userByRetailerId = userByRetailerId;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}

	public CustomerRetailer(User userByCustomerId, User userByRetailerId) {
		this.userByCustomerId = userByCustomerId;
		this.userByRetailerId = userByRetailerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUserByCustomerId() {
		return this.userByCustomerId;
	}

	public void setUserByCustomerId(User userByCustomerId) {
		this.userByCustomerId = userByCustomerId;
	}

	public User getUserByRetailerId() {
		return this.userByRetailerId;
	}

	public void setUserByRetailerId(User userByRetailerId) {
		this.userByRetailerId = userByRetailerId;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public int getObjectVersionNumber() {
		return objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

}
