package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * OrderLines generated by hbm2java
 */
@XStreamAlias("order_line")
@Entity
public class OrderLines implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	@JsonIgnore
	private Orders orders;
	@JsonIgnore
	private Product product;
	@JsonIgnore
	private Organization organization;
	private int quantity;
	private int packaged;
	private float price;
	private float tax;
	private float discount;
	private int createdBy;
	private int lastUpdatedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	@Version
	private int objectVersionNumber;

	public OrderLines() {
	}

	public OrderLines(Orders orders, Product product, int quantity,
			int packaged, float price, float tax, float discount,
			int createdBy, int lastUpdatedBy, Date creationDate,
			Date lastUpdatedDate, int objectVersionNumber) {
		this.orders = orders;
		this.product = product;
		this.quantity = quantity;
		this.packaged = packaged;
		this.price = price;
		this.tax = tax;
		this.discount = discount;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}

	public OrderLines(Orders orders, Product product,
			Organization organization, int quantity, int packaged, float price,
			float tax, float discount, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber) {
		this.orders = orders;
		this.product = product;
		this.organization = organization;
		this.quantity = quantity;
		this.packaged = packaged;
		this.price = price;
		this.tax = tax;
		this.discount = discount;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public float getTax() {
		return this.tax;
	}

	public void setTax(float tax) {
		this.tax = tax;
	}

	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

	public int getPackaged() {
		return packaged;
	}

	public void setPackaged(int packaged) {
		this.packaged = packaged;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("OrderLines [id=");
		builder.append(id);
//		builder.append(", orders=");
//		builder.append(orders);
		builder.append(", product=");
		builder.append(product);
		builder.append(", quantity=");
		builder.append(quantity);
		builder.append(", price=");
		builder.append(price);
		builder.append(", tax=");
		builder.append(tax);
		builder.append(", discount=");
		builder.append(discount);
		builder.append(", createdBy=");
		builder.append(createdBy);
		builder.append(", lastUpdatedBy=");
		builder.append(lastUpdatedBy);
		builder.append(", creationDate=");
		builder.append(creationDate);
		builder.append(", lastUpdatedDate=");
		builder.append(lastUpdatedDate);
		builder.append(", objectVersionNumber=");
		builder.append(objectVersionNumber);
		builder.append("]");
		return builder.toString();
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("orders", Orders.class);
		xstreamObj.alias("product", Product.class);
		xstreamObj.alias("organization", Organization.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}

}
