package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Orders generated by hbm2java
 */
@XStreamAlias("order")
@Entity
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	@XStreamAlias("customer")
	private User user;
	@XStreamAlias("shipping_address")
	private Address addressByShippingAddressId;
	private Organization organization;
	@XStreamAlias("retialer")
	private User userByRetailerId;
	@XStreamAlias("billing_address")
	private Address addressByBillingAddressId;
	@XStreamAlias("new")
	private boolean isNew;
	private int priority;
	private String status;
	private String comments;
	private float itemValue;
	private float tax;
	private float commission;
	private String ip;
	@XStreamAlias("expected_delivery_time")
	private Date expectedDeliveryTime;
	private int createdBy;
	private int lastUpdatedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	@Version
	private int objectVersionNumber;
	private String type;
	private String deliveryCode;
	private String orderNumber;
	@XStreamOmitField	
	@JsonIgnore
	private Set<OrderLines> orderLineses = new HashSet<OrderLines>(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set<OrderHistory> orderHistories = new HashSet<OrderHistory>(0);

	public Orders() {
	}

	public Orders(int id) {
		this.id = id;
	}

	public Orders(User user, Address addressByShippingAddressId,
			Address addressByBillingAddressId, String status, float itemValue,
			float tax, float commission, String ip, int createdBy,
			int lastUpdatedBy, Date creationDate, Date lastUpdatedDate,
			int objectVersionNumber, String type, boolean isNew, int priority) {
		this.user = user;
		this.addressByShippingAddressId = addressByShippingAddressId;
		this.addressByBillingAddressId = addressByBillingAddressId;
		this.status = status;
		this.itemValue = itemValue;
		this.tax = tax;
		this.commission = commission;
		this.ip = ip;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.type = type;
		this.isNew = isNew;
		this.priority = priority;
	}

	public Orders(User user, Address addressByShippingAddressId,
			Organization organization, Address addressByBillingAddressId,
			String status, String comments, float itemValue, float tax,
			float commission, String ip, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber, String type,
			Date expectedDeliveryTime, String deliveryCode, String orderNumber,
			Set<OrderLines> orderLineses, Set<OrderHistory> orderHistories) {
		this.user = user;
		this.addressByShippingAddressId = addressByShippingAddressId;
		this.organization = organization;
		this.addressByBillingAddressId = addressByBillingAddressId;
		this.status = status;
		this.comments = comments;
		this.itemValue = itemValue;
		this.tax = tax;
		this.commission = commission;
		this.ip = ip;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.type = type;
		this.expectedDeliveryTime = expectedDeliveryTime;
		this.deliveryCode = deliveryCode;
		this.orderNumber = orderNumber;
		this.orderLineses = orderLineses;
		this.orderHistories = orderHistories;
	}
		public Orders(User user, String status, Address addressByBillingAddressId,
				Address addressByShippingAddressId, float itemValue, float tax,
			float commission, String ip, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber,
			String type, boolean isNew, int priority) {
		this.user = user;
		this.status = status;
		this.addressByBillingAddressId = addressByBillingAddressId;
		this.addressByShippingAddressId = addressByShippingAddressId;
		this.itemValue = itemValue;
		this.tax = tax;
		this.commission = commission;
		this.ip = ip;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.type = type;
		this.isNew = isNew;
		this.priority = priority;
	}

	public Orders(User user, Address addressByShippingAddressId,
			Organization organization, Address addressByBillingAddressId,
			String status, String comments, float itemValue, float tax,
			float commission, String ip, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber,
			String type, Date expectedDeliveryTime, String deliveryCode,
			String orderNumber, boolean isNew, int priority, Set orderLineses,
			Set orderHistories) {
		this.user = user;
		this.addressByShippingAddressId = addressByShippingAddressId;
		this.organization = organization;
		this.addressByBillingAddressId = addressByBillingAddressId;
		this.status = status;
		this.comments = comments;
		this.itemValue = itemValue;
		this.tax = tax;
		this.commission = commission;
		this.ip = ip;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.type = type;
		this.expectedDeliveryTime = expectedDeliveryTime;
		this.deliveryCode = deliveryCode;
		this.orderNumber = orderNumber;
		this.isNew = isNew;
		this.priority = priority;
		this.orderLineses = orderLineses;
		this.orderHistories = orderHistories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Address getAddressByShippingAddressId() {
		return this.addressByShippingAddressId;
	}

	public void setAddressByShippingAddressId(Address addressByShippingAddressId) {
		this.addressByShippingAddressId = addressByShippingAddressId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Address getAddressByBillingAddressId() {
		return this.addressByBillingAddressId;
	}

	public void setAddressByBillingAddressId(Address addressByBillingAddressId) {
		this.addressByBillingAddressId = addressByBillingAddressId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public float getItemValue() {
		return this.itemValue;
	}

	public void setItemValue(float itemValue) {
		this.itemValue = itemValue;
	}

	public float getTax() {
		return this.tax;
	}

	public void setTax(float tax) {
		this.tax = tax;
	}

	public float getCommission() {
		return this.commission;
	}

	public void setCommission(float commission) {
		this.commission = commission;
	}

	public String getIp() {
		return this.ip;
	}

	public Date getExpectedDeliveryTime() {
		return expectedDeliveryTime;
	}

	public void setExpectedDeliveryTime(Date expectedDeliveryTime) {
		this.expectedDeliveryTime = expectedDeliveryTime;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}
	
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}


	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}


	public String getDeliveryCode() {
		return this.deliveryCode;
	}

	public void setDeliveryCode(String deliveryCode) {
		this.deliveryCode = deliveryCode;
	}

	public Set<OrderLines> getOrderLineses() {
		return this.orderLineses;
	}

	public void setOrderLineses(Set<OrderLines> orderLineses) {
		this.orderLineses = orderLineses;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Orders [id=");
		builder.append(id);
		builder.append(", addressByShippingAddressId=");
		builder.append(addressByShippingAddressId);
		builder.append(", userByRetailerId=");
		builder.append(userByRetailerId);
		builder.append(", addressByBillingAddressId=");
		builder.append(addressByBillingAddressId);
		builder.append(", status=");
		builder.append(status);
		builder.append(", comments=");
		builder.append(comments);
		builder.append(", itemValue=");
		builder.append(itemValue);
		builder.append(", tax=");
		builder.append(tax);
		builder.append(", commission=");
		builder.append(commission);
		builder.append(", ip=");
		builder.append(ip);
		builder.append(", createdBy=");
		builder.append(createdBy);
		builder.append(", lastUpdatedBy=");
		builder.append(lastUpdatedBy);
		builder.append(", creationDate=");
		builder.append(creationDate);
		builder.append(", lastUpdatedDate=");
		builder.append(lastUpdatedDate);
		builder.append(", objectVersionNumber=");
		builder.append(objectVersionNumber);
		builder.append(", type=");
		builder.append(type);
		builder.append("]");
		return builder.toString();
	}
	
	public Set getOrderHistories() {
		return this.orderHistories;
	}

	public void setOrderHistories(Set<OrderHistory> orderHistories) {
		this.orderHistories = orderHistories;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}
	
	public boolean getIsNew() {
		return isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("user", User.class);
		xstreamObj.alias("addressByShippingAddressId", Address.class);
		xstreamObj.alias("organization", Organization.class);
		xstreamObj.alias("userByRetailerId", User.class);
		xstreamObj.alias("addressByBillingAddressId", Address.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
