package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Organization generated by hbm2java
 */
@XStreamAlias("organization")
@Entity
public class Organization implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int id;
	@JsonIgnore
	private Address address;
	private String name;
	private String orgType;
	private String ownerName;
	private int yearOfEstablishment;
	private int serviceArea;
	private int minPurchaseAmount;
	private int defaultDeliveryTime;
	private int createdBy;
	private int lastUpdatedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	@Version
	private int objectVersionNumber;
	@XStreamOmitField	
	@JsonIgnore
	private Set<Orders> orderses = new HashSet<Orders>(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set<OrderLines> orderLineses = new HashSet<OrderLines>(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set<RetailerSnapshot> retailerSnapshots = new HashSet<RetailerSnapshot>(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set<User> users = new HashSet<User>(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set orderHistories = new HashSet(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set retailerZones = new HashSet(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set retailerCategories = new HashSet(0);

	public Organization() {
	}
	
	public Organization(int orgId) {
		this.id = orgId;
	}

	public Organization(Address address, String name, String orgType,
			int createdBy, int lastUpdatedBy, Date creationDate,
			Date lastUpdatedDate, int objectVersionNumber) {
		this.address = address;
		this.name = name;
		this.orgType = orgType;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}
	public Organization(Address address, String name, String orgType) {
		this.address = address;
		this.name = name;
		this.orgType = orgType;
		this.createdBy = 1;
		this.lastUpdatedBy = 1;
		this.creationDate = new Date();
		this.lastUpdatedDate = new Date();
		this.objectVersionNumber = 1;
	}

	public Organization(Address address, String name, String orgType,
			int createdBy, int lastUpdatedBy, Date creationDate,
			Date lastUpdatedDate, int objectVersionNumber, Set<Orders> orderses,
			Set<OrderLines> orderLineses,
			Set<RetailerSnapshot> retailerSnapshots, Set<User> users,
			Set<OrderHistory> orderHistories) {
		this.address = address;
		this.name = name;
		this.orgType = orgType;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.orderses = orderses;
		this.orderLineses = orderLineses;
		this.retailerSnapshots = retailerSnapshots;
		this.users = users;
		this.orderHistories = orderHistories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrgType() {
		return this.orgType;
	}

	public void setOrgType(String orgType) {
		this.orgType = orgType;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	public Set<OrderLines> getOrderLineses() {
		return this.orderLineses;
	}

	public void setOrderLineses(Set<OrderLines> orderLineses) {
		this.orderLineses = orderLineses;
	}

	public Set getRetailerZones() {
		return this.retailerZones;
	}

	public void setRetailerZones(Set retailerZones) {
		this.retailerZones = retailerZones;
	}

	public Set<RetailerSnapshot> getRetailerSnapshots() {
		return this.retailerSnapshots;
	}

	public void setRetailerSnapshots(Set<RetailerSnapshot> retailerSnapshots) {
		this.retailerSnapshots = retailerSnapshots;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<OrderHistory> getOrderHistories() {
		return this.orderHistories;
	}

	public void setOrderHistories(Set<OrderHistory> orderHistories) {
		this.orderHistories = orderHistories;
	}

	public Set getRetailerCategories() {
		return this.retailerCategories;
	}

	public void setRetailerCategories(Set retailerCategories) {
		this.retailerCategories = retailerCategories;
	}

	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public int getYearOfEstablishment() {
		return yearOfEstablishment;
	}

	public void setYearOfEstablishment(int yearOfEstablishment) {
		this.yearOfEstablishment = yearOfEstablishment;
	}

	public int getServiceArea() {
		return serviceArea;
	}

	public void setServiceArea(int serviceArea) {
		this.serviceArea = serviceArea;
	}

	public int getMinPurchaseAmount() {
		return minPurchaseAmount;
	}

	public void setMinPurchaseAmount(int minPurchaseAmount) {
		this.minPurchaseAmount = minPurchaseAmount;
	}

	public int getDefaultDeliveryTime() {
		return defaultDeliveryTime;
	}

	public void setDefaultDeliveryTime(int defaultDeliveryTime) {
		this.defaultDeliveryTime = defaultDeliveryTime;
	}
}
