package com.tresfocus.ekart.hibernate.entity;

// Generated Jul 13, 2014 7:56:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * States generated by hbm2java
 */
@XStreamAlias("state")
@Entity
public class States implements java.io.Serializable {

	private int id;
	private Country country;
	private String name;
	@XStreamOmitField	
	@JsonIgnore
	private Set citieses = new HashSet(0);

	public States() {
	}

	public States(Country country, String name) {
		this.country = country;
		this.name = name;
	}

	public States(Country country, String name, Set citieses) {
		this.country = country;
		this.name = name;
		this.citieses = citieses;
	}

	public States(Integer stateId) {
		this.id = stateId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCitieses() {
		return this.citieses;
	}

	public void setCitieses(Set citieses) {
		this.citieses = citieses;
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("cities", Cities.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
