package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * User generated by hbm2java
 */

@XStreamAlias("user")
@Entity
public class User implements java.io.Serializable {

	private int id;
	private Organization organization;
	private boolean active = true;
	private String username;
	@XStreamOmitField	
	private String password;
	private String fname;
	private String lname;
	private String gender;
	private String email;
	private String phone;
	private String operatingCurrency;
	private String timezone;
	private int createdBy;
	private int lastUpdatedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	@Version
	private int objectVersionNumber;
	@XStreamOmitField
	@JsonIgnore
	private Set<Orders> orderses = new HashSet<Orders>(0);
	@XStreamOmitField
	@JsonIgnore
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
	@XStreamOmitField
	//@JsonIgnore
	private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);
	@XStreamOmitField
	@JsonIgnore
	private Set customerRetailersForRetailerId = new HashSet(0);
	@XStreamOmitField
	@JsonIgnore
	private Set customerRetailersForCustomerId = new HashSet(0);

	public User() {
	}

	public User(int id) {
		this.id = id;
	}
	
	public User(boolean active, String username, String password,
			int createdBy, int lastUpdatedBy, Date creationDate,
			Date lastUpdatedDate, int objectVersionNumber) {
		this.active = active;
		this.username = username;
		this.password = password;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}
	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(Organization organization, boolean active, String username,
			String password, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber, Set<Orders> orderses,
Set retailerCategories,
			Set<UserRole> userRoles, Set<UserAddress> userAddresses,Set customerRetailersForRetailerId) {
		this.organization = organization;
		this.active = active;
		this.username = username;
		this.password = password;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.customerRetailersForCustomerId = customerRetailersForCustomerId;
		this.orderses = orderses;
		this.userRoles = userRoles;
		this.userAddresses = userAddresses;
		this.customerRetailersForRetailerId = customerRetailersForRetailerId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getOperatingCurrency() {
		return this.operatingCurrency;
	}

	public void setOperatingCurrency(String operatingCurrency) {
		this.operatingCurrency = operatingCurrency;
	}

	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

	public Set getCustomerRetailersForCustomerId() {
		return this.customerRetailersForCustomerId;
	}

	public void setCustomerRetailersForCustomerId(
			Set customerRetailersForCustomerId) {
		this.customerRetailersForCustomerId = customerRetailersForCustomerId;
	}
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

	public Set getCustomerRetailersForRetailerId() {
		return this.customerRetailersForRetailerId;
	}

	public void setCustomerRetailersForRetailerId(
			Set customerRetailersForRetailerId) {
		this.customerRetailersForRetailerId = customerRetailersForRetailerId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("User [id=");
		builder.append(id);
		builder.append(", active=");
		builder.append(active);
		builder.append(", username=");
		builder.append(username);
		builder.append(", createdBy=");
		builder.append(createdBy);
		builder.append(", lastUpdatedBy=");
		builder.append(lastUpdatedBy);
		builder.append(", creationDate=");
		builder.append(creationDate);
		builder.append(", lastUpdatedDate=");
		builder.append(lastUpdatedDate);
		builder.append(", objectVersionNumber=");
		builder.append(objectVersionNumber);
		builder.append("]");
		return builder.toString();
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("organization", Organization.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
