package com.tresfocus.ekart.hibernate.entity;

// Generated May 10, 2014 2:51:46 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

/**
 * Zone generated by hbm2java
 */
@XStreamAlias("zone")
@Entity
public class Zone implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Cities cities;
	private String name;
	private int createdBy;
	private int lastUpdatedBy;
	private Date creationDate;
	private Date lastUpdatedDate;
	@Version
	private int objectVersionNumber;
	@XStreamOmitField	
	@JsonIgnore
	private Set retailerCategories = new HashSet(0);
	@XStreamOmitField	
	@JsonIgnore
	private Set retailerZones = new HashSet(0);

	public Zone() {
	}

	public Zone(Cities cities, String name, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber) {
		this.cities = cities;
		this.name = name;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
	}

	public Zone(Cities cities, String name, int createdBy, int lastUpdatedBy,
			Date creationDate, Date lastUpdatedDate, int objectVersionNumber,
			Set retailerCategories, Set retailerZones) {
		this.cities = cities;
		this.name = name;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.creationDate = creationDate;
		this.lastUpdatedDate = lastUpdatedDate;
		this.objectVersionNumber = objectVersionNumber;
		this.retailerCategories = retailerCategories;
		this.retailerZones = retailerZones;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cities getCities() {
		return this.cities;
	}

	public void setCities(Cities cities) {
		this.cities = cities;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public int getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(int objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

	public Set getRetailerCategories() {
		return this.retailerCategories;
	}

	public void setRetailerCategories(Set retailerCategories) {
		this.retailerCategories = retailerCategories;
	}

	public Set getRetailerZones() {
		return this.retailerZones;
	}

	public void setRetailerZones(Set retailerZones) {
		this.retailerZones = retailerZones;
	}

	public static void initializeXStream(XStream xstreamObj) {
		xstreamObj.alias("cities", Cities.class);
		xstreamObj.alias("", java.sql.Timestamp.class, java.util.Date.class);		
	}
}
